version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"   # เปิด port PostgreSQL ออกไปให้ client เชื่อมต่อ
    volumes:
      - ./pgdata:/var/lib/postgresql/data
