import type { Metadata } from "next";
import { Inter } from "next/font/google"; // 1. เปลี่ยน import เป็น Inter
import "./globals.css";
import { Providers } from "./providers";

// 2. สร้าง instance ของ Inter
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // 3. เรียกใช้ className ของ inter ตรงนี้แทน variable เดิม
        className={inter.className}
        suppressHydrationWarning
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}